# Set Shell fish
# Sleep 500ms

Set FontSize 32
Set Width 3000
Set Height 1500
Set Theme "Catppuccin Mocha"
Set FontFamily "Geist Mono"

Output demo.gif
Type "splitrail"
Enter
Sleep 2.5s
PageDown 17
Sleep 1s
Up 9
Sleep 2s
Enter
Down 27
Sleep 2s
Up 9
Sleep 2s
Ctrl+T
Sleep 1s
Right 1
Sleep 1s
Right 1
Sleep 1s
Right 1
Sleep 1s
Down 7
Sleep 1.5s
Enter
Down 2
Sleep 2s
Up 2
Sleep 1s
Ctrl+T
Sleep 2s
Right
Down 8
Sleep 1s
Left 3
Sleep 2s
Left
Sleep 2s
Down 56
Sleep 2s
PageDown 21
Sleep 2s
